#!/usr/bin/env bash
# 03-network.sh — WP-H2: the network wall, keyed on resident uids.
#
# RUN BY: plink, with sudo, AFTER 01-users.sh (rules reference the resident
# usernames, which must resolve when the ruleset loads).
# Idempotent: rewrites its own nftables file, its own table, its own refresh
# units; touches nothing else in your firewall.
#
# THE PROMISE THIS SCRIPT KEEPS (Claudette's boundary flag, HARNESS-PLAN
# WP-H2): "podman rootless" and "my egress is actually walled" are two
# separate promises. Enforcement lives HERE, in host netfilter, matched on
# the kernel uid of the sending socket (meta skuid). Rootless podman's
# user-mode networking (slirp4netns/pasta) runs AS the resident uid, so every
# packet a resident container emits carries that uid on the host — and hits
# these rules. Nothing inside a container can reach or edit this policy.
#
# Policy per resident uid, allow-list, default drop:
#   1. loopback TCP to 8399           — the Disjorn server, their home
#   2. TCP 443 to api.anthropic.com   — their model API (via named nft sets,
#                                       refreshed because the IPs rotate)
#   3. DNS to the LOCAL resolver only — no tunneling questions to 8.8.8.8
#   4. everything else: log (rate-limited) + drop
# Additions (e.g. Ollama) happen by plink editing this file — deliberately.
set -euo pipefail

RESIDENTS='"res-claudette", "res-gable"'
NFT_DIR=/etc/nftables.d
NFT_FILE=$NFT_DIR/disjorn-residents.nft
REFRESH=/usr/local/sbin/disjorn-anthropic-refresh

# The local resolver residents may query. Auto-detected from resolv.conf
# (127.0.0.53 when systemd-resolved). CHECK the echoed value: if it is a LAN
# router, that hole is "DNS to the router", which is still the local resolver
# but crosses the wire — acceptable, just be aware.
RESOLVER=$(awk '/^nameserver/ {print $2; exit}' /etc/resolv.conf)
echo "== resident DNS will be allowed only to: $RESOLVER"

mkdir -p "$NFT_DIR"

# --- the ruleset ------------------------------------------------------------
cat > "$NFT_FILE" <<EOF
# Disjorn resident egress wall (WP-H2) — generated by 03-network.sh.
# Matched on 'meta skuid': the uid owning the sending socket. Applies to
# resident processes AND their rootless-podman container traffic (the
# user-mode network proxy runs as the resident uid).

table inet disjorn_residents        # our own table; deleted+reloaded on re-run
delete table inet disjorn_residents

table inet disjorn_residents {
  # api.anthropic.com resolves to rotating IPs -> named sets, repopulated by
  # $REFRESH (systemd timer, every 10 min). Interval flag so
  # the refresher could add CIDRs; timeout not used - refresh replaces content.
  set anthropic_v4 { type ipv4_addr; flags interval; }
  set anthropic_v6 { type ipv6_addr; flags interval; }

  chain output {
    type filter hook output priority filter; policy accept;
    # Only resident-uid packets enter the wall; everyone else is untouched.
    meta skuid { $RESIDENTS } jump resident_wall
  }

  chain resident_wall {
    # 1. Disjorn itself: loopback only, the one port.
    oif "lo" tcp dport 8399 accept

    # 2. Their model API: 443 to whatever api.anthropic.com currently is.
    ip  daddr @anthropic_v4 tcp dport 443 accept
    ip6 daddr @anthropic_v6 tcp dport 443 accept

    # 3. DNS: local resolver only (udp + tcp for large answers).
    ip daddr $RESOLVER udp dport 53 accept
    ip daddr $RESOLVER tcp dport 53 accept

    # 4. Everything else from a resident uid dies here, visibly.
    limit rate 6/minute log prefix "disjorn-wall-drop " counter drop
    counter drop
  }
}
EOF

# --- refresh script for the anthropic sets ---------------------------------
cat > "$REFRESH" <<'EOF'
#!/usr/bin/env bash
# disjorn-anthropic-refresh — repopulate the nftables sets holding
# api.anthropic.com's current addresses (they rotate; the wall follows).
# Installed by harness/keyboard/03-network.sh; run by systemd timer.
set -euo pipefail
HOST=api.anthropic.com
v4=$(getent ahostsv4 "$HOST" | awk '{print $1}' | sort -u || true)
v6=$(getent ahostsv6 "$HOST" | awk '{print $1}' | grep -v '\.' | sort -u || true)
# Refuse to empty the set on a failed lookup — better stale than broken.
[ -n "$v4" ] || { echo "no v4 answer for $HOST; keeping old set" >&2; exit 0; }
nft flush set inet disjorn_residents anthropic_v4
for ip in $v4; do nft add element inet disjorn_residents anthropic_v4 "{ $ip }"; done
if [ -n "$v6" ]; then
  nft flush set inet disjorn_residents anthropic_v6
  for ip in $v6; do nft add element inet disjorn_residents anthropic_v6 "{ $ip }"; done
fi
EOF
chmod 0755 "$REFRESH"

# --- systemd service + timer for the refresh --------------------------------
cat > /etc/systemd/system/disjorn-anthropic-refresh.service <<EOF
[Unit]
Description=Refresh nftables sets for api.anthropic.com (Disjorn resident wall)
[Service]
Type=oneshot
ExecStart=$REFRESH
EOF

cat > /etc/systemd/system/disjorn-anthropic-refresh.timer <<'EOF'
[Unit]
Description=Refresh Disjorn resident wall's anthropic IP sets every 10 min
[Timer]
OnBootSec=1min
OnUnitActiveSec=10min
[Install]
WantedBy=timers.target
EOF

# --- load now + persist across reboots --------------------------------------
nft -f "$NFT_FILE"
"$REFRESH"

# Persist: Debian loads /etc/nftables.conf at boot via nftables.service.
if ! grep -qF "$NFT_FILE" /etc/nftables.conf; then
  printf '\ninclude "%s"\n' "$NFT_FILE" >> /etc/nftables.conf
  echo "== appended include line to /etc/nftables.conf"
fi
systemctl enable --now nftables
systemctl daemon-reload
systemctl enable --now disjorn-anthropic-refresh.timer

echo
echo "Verify: nft list table inet disjorn_residents"
echo "        sudo -u res-gable curl -sm5 https://example.com   (expect: timeout)"
echo "        journalctl -k | grep disjorn-wall-drop            (the drops, logged)"
