"""Resident bootstrap (WP-H7's assembly step): spine -> ~/.claude/CLAUDE.md.

Runs IN the resident's own namespace (container or host session) before a
CC session starts:  python3 /opt/house_memory/house_memory/bootstrap.py
(direct-file invocation on purpose: the package __init__ imports the chroma
stack, which a bare container python doesn't have and this script doesn't need)

Assembles the kernel from the resident's git-versioned spine, writes the
MEMORY.md index, and scaffolds the memory dir. Idempotent — re-runs simply
re-derive both files from the spine, so a spine edit (witnessed, merged)
reaches the next session with no extra step.

Paths come ONLY from env — never hardcoded homes. The res-gable-vs-resident
path split (host view vs container view of the same volume) is exactly the
socket-inode bug's cousin; whoever RUNS this supplies THEIR view:

    RESIDENT_SPINE_DIR   spine directory (required; no guessing)
    RESIDENT_MEMORY_DIR  episodic dir     (default $HOME/memory)
    RESIDENT_SEAT        which seat this session is (default 'resident'; the
                         run-resident.sh / run-build.sh wrappers set it)
    HOME                 target for .claude/CLAUDE.md and MEMORY.md

SEAT (spec 2026-07-22 seat-split). One spine of record serves two seats:
  * resident (default) — a summon; bakes the kernel, retrieves the rest;
    BYTE-IDENTICAL to pre-seat behaviour for a given spine.
  * build              — a detached CC build session; bakes the operational
    set (it has no retrieval loop) and never sees biography.
An UNSET or empty RESIDENT_SEAT is the resident seat — the zero-regression
default. An UNKNOWN seat name is a hard error (return 2), never a silent
fallback: the wrong seat would either strip a resident's identity or leak
biography into a build, so we fail closed and loud.

Imports only house_memory.spine (pure stdlib) — no chroma/voyage, so it
runs on a bare python3. The episodic store itself is NOT created here:
that needs the embedding stack and lands with the resident's memory
tooling; an empty memory dir is correct for a new resident.
"""

import os
import sys
import time
from pathlib import Path

if __package__:
    from .spine import SEATS, Spine
else:  # direct-file run: import spine.py from this dir, skip package __init__
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from spine import SEATS, Spine


def main() -> int:
    home = Path(os.environ.get("HOME", ""))
    spine_dir = os.environ.get("RESIDENT_SPINE_DIR")
    if not home or not spine_dir:
        print("bootstrap: HOME and RESIDENT_SPINE_DIR are required", file=sys.stderr)
        return 2

    # Seat: UNSET/empty is the resident seat (zero-regression default). An
    # unknown name fails closed and loud rather than guessing.
    seat = os.environ.get("RESIDENT_SEAT") or "resident"
    if seat not in SEATS:
        print(f"bootstrap: unknown RESIDENT_SEAT {seat!r}; valid: {sorted(SEATS)}",
              file=sys.stderr)
        return 2

    memory_dir = Path(os.environ.get("RESIDENT_MEMORY_DIR", home / "memory"))

    spine = Spine(spine_dir)
    # Seat-gated everywhere: the index lists only what this seat loads, and the
    # bake is this seat's policy (resident=kernel-only+retrieve; build=all
    # visible). For the resident seat both reduce to today's behaviour.
    # Redline 1 failures (an entry with no `seats:` declaration; no kernel
    # entry visible to this seat) surface here as ValueError — turn them into
    # the same loud exit-2 every other bootstrap refusal uses, message intact.
    try:
        entries = spine.entries_for_seat(seat)
        kernel = spine.assemble_for_seat(seat)
    except ValueError as e:
        print(f"bootstrap: {e}", file=sys.stderr)
        return 2
    if not kernel.strip():
        print(f"bootstrap: spine at {spine_dir} assembles empty for seat {seat!r}",
              file=sys.stderr)
        return 2

    stamp = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    kernel_path = home / ".claude" / "CLAUDE.md"
    kernel_path.parent.mkdir(parents=True, exist_ok=True)
    kernel_path.write_text(
        kernel + f"\n\n<!-- assembled from {spine_dir} (seat: {seat}) at {stamp} -->\n",
        encoding="utf-8")

    lines = [
        "# MEMORY.md — spine index (auto-generated by house_memory.bootstrap;",
        f"# derived from {spine_dir} (seat: {seat}) at {stamp} — edit the spine, not this file)",
        "",
    ]
    for e in entries:
        first = next((ln.strip().lstrip("# ") for ln in e.body.splitlines()
                      if ln.strip()), "")
        tag = " [kernel]" if e.kernel else ""
        lines.append(f"- [{e.name}]({e.path}){tag} — {first[:100]}")
    lines += [
        "",
        "Episodic store: not yet initialized (empty memory dir is correct for",
        "a new resident; the store arrives with the memory tooling).",
    ]
    (home / "MEMORY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    memory_dir.mkdir(parents=True, exist_ok=True)

    print(f"bootstrap: seat {seat}; kernel {len(kernel)} chars -> {kernel_path}; "
          f"{len(entries)} spine entries indexed; memory dir {memory_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
